### ISSUE TITLE
feat(pkg): Alpine package (.apk)

### ISSUE THREAD

**Issue by grencez** [fildesh/fildesh#157]
I would like an Alpine package for Fildesh so that I can install & use it on more machines.

**Comment by grencez** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/71636

**Comment by chrisleviss** [comment]
The user appreciates the initiative to develop an Alpine package for Fildesh, which would significantly enhance its accessibility across multiple machines. It’s encouraging to see @grencez actively working on this feature, adding relevant commits and addressing associated tasks. The user's interest aligns well with the ongoing developments, and they suggest that exploring resources like [liteapkz](https://www.liteapkz.com/) could provide additional insights or tools that might aid in this process. Collaborative efforts will surely contribute to making Fildesh more widely usable, and the user looks forward to the outcome of this feature.
